name: Sync LeetCode

on:
  workflow_dispatch:

  schedule:
    # Every day at 12:00 AM UTC
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync Accepted Solutions
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode to GitHub
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}

          # Save all solutions inside this folder
          destination-folder: LeetCode

          # Show detailed logs
          verbose: true

          # Commit message
          commit-header: "[LeetCode Sync]"
